name: CI Workflow

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request to the main branch

jobs:
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Client
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies for Client
        run: |
          cd client
          npm install

      - name: Run ESLint for Client
        run: |
          cd client
          npx eslint . --max-warnings=0

  lint-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Server
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies for Server
        run: |
          cd server
          npm install

      - name: Run ESLint for Server
        run: |
          cd server
          npx eslint . --max-warnings=0

  trigger-netlify:
    runs-on: ubuntu-latest
    needs:
      - lint-client
      - lint-server
    steps:
      - name: Trigger Netlify Build
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: |
          curl -X POST -d {} $NETLIFY_BUILD_HOOK
