name: CI Workflow

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request to the main branch

jobs:
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Client
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify Node.js version

      - name: Install dependencies for Client
        run: |
          cd client
          npm install

      - name: Run ESLint for Client
        run: |
          cd client
          npx eslint . --max-warnings=0  # Fail the build on warnings

  lint-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Server
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify Node.js version

      - name: Install dependencies for Server
        run: |
          cd server
          npm install

      - name: Run ESLint for Server
        run: |
          cd server
          npx eslint . --max-warnings=0  # Fail the build on warnings

  netlify-deploy:
    runs-on: ubuntu-latest
    needs:
      - lint-client
      - lint-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npx netlify deploy --prod --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
